apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
  labels:
    app: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare-app
        image: chandan3461/healthcare-app:latest # Replace with your DockerHub image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  type: NodePort
  selector:
    app: healthcare
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30008 # Replace with your desired NodePort (in the range 30000-32767)

