apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  type: NodePort
  selector:
    app: healthcare
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30008 # Replace with your desired NodePort (in the range 30000-32767)

